# Generated by Django 4.2.5 on 2023-09-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Превью')),
                ('date_create', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('count_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
        ),
    ]
