# Generated by Django 4.2.5 on 2023-10-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя версии'),
        ),
    ]
